spring.application.name=eztasks
spring.datasource.url=jdbc:postgresql://ep-broad-rice-aogfecxo-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fB9HtAoqOvI3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
server.port=8080
eztasks.seed.enabled=false

# JWT Configuration
jwt.secret=eztasks-secret-key-for-jwt-token-generation-minimum-256-bits-required-for-hmac-sha-256-algorithm-security
jwt.expiration=86400000